# -*- coding: utf-8 -*-
"""sqpair_floorplanning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19ndW6tMrvF-WYeG_2-R34ajiLy9vTBRh
"""
import math
import random

class Module:
  def __init__(self, name, area, aspect_ratios):
    self._name = name
    self._area = area
    self._wh = [(math.sqrt(area*r), math.sqrt(area/r)) for r in aspect_ratios]
  def __repr__(self):
    return f"’{self._name} area:{self._area} xy:{self._wh}’"

class SeqPair:
  def __init__(self, modules):
    self._pos = [i for i in range(len(modules))]
    self._neg = [i for i in range(len(modules))]
    self._ap = [0 for i in range(len(modules))]
    self._coords = [(0,0) for i in range(len(modules))]
    self._w = 0
    self._h = 0
  def __getitem__(self, key):
    if key == slice(None):
        new_S = SeqPair([])
        new_S._pos = self._pos[:]
        new_S._neg = self._neg[:]
        new_S._ap = self._ap[:]
        new_S._coords = self._coords[:]
        new_S._w = self._w
        new_S._h = self._h
        return new_S
    raise TypeError("Only full slicing [:] is supported for SeqPair deep copy.")

  def perturb(self, modules):
    new_S = self[:] # Create a completely new copy to perturb
    n = len(modules)
    if n < 2:
        return new_S

    choice = random.randint(1, 4)

    if choice in [1, 2, 3]:
        i, j = random.sample(range(n), 2)
        if choice == 1:
            new_S._pos[i], new_S._pos[j] = new_S._pos[j], new_S._pos[i]
        elif choice == 2:
            new_S._neg[i], new_S._neg[j] = new_S._neg[j], new_S._neg[i]
        elif choice == 3:
            new_S._pos[i], new_S._pos[j] = new_S._pos[j], new_S._pos[i]
            new_S._neg[i], new_S._neg[j] = new_S._neg[j], new_S._neg[i]

    elif choice == 4:
        i = random.randint(0, n - 1)
        num_ratios = len(modules[i]._wh)
        if num_ratios > 1:
            current_ap = new_S._ap[i]
            possible_aps = [r for r in range(num_ratios) if r != current_ap]
            new_S._ap[i] = random.choice(possible_aps)

    return new_S

  def costEval(self, modules):
    n = len(modules)
    W = [0] * n
    H = [0] * n
    X = [0] * n
    Y = [0] * n

    for i in range(n):
        W[i], H[i] = modules[i]._wh[self._ap[i]]

    # X coordinates (HCG)
    for i in range(n):
        mod_A = self._pos[i]
        pos_A_in_neg = self._neg.index(mod_A)
        for j in range(i + 1, n):
            mod_B = self._pos[j]
            pos_B_in_neg = self._neg.index(mod_B)
            if pos_A_in_neg < pos_B_in_neg:
                X[mod_B] = max(X[mod_B], X[mod_A] + W[mod_A])

    # Y coordinates (VCG)
    for i in range(n):
        mod_A = self._neg[i]
        pos_A_in_pos = self._pos.index(mod_A)
        for j in range(i + 1, n):
            mod_B = self._neg[j]
            pos_B_in_pos = self._pos.index(mod_B)
            if pos_A_in_pos > pos_B_in_pos:
                Y[mod_B] = max(Y[mod_B], Y[mod_A] + H[mod_A])

    for i in range(n):
        self._coords[i] = (X[i], Y[i])

    self._w = max([X[i] + W[i] for i in range(n)])
    self._h = max([Y[i] + H[i] for i in range(n)])

    return self._w * self._h

import math
import random
def accept(delC, T):
  if delC <= 0: return True
  return random.random() < math.exp(-delC/T)
# S = Initial sequence pair, choice of aspect ratio
def simulated_annealing(Tmin, Tmax, N, alpha, S, modules, plot):
  assert(alpha < 1. and Tmin < Tmax)
  T = Tmax
  C = S.costEval(modules)
  minC = C
  minS = S[:]
  Clist = []
  Temp = []
  while T > Tmin:
    for i in range(N):
      Snew = S.perturb(modules)
      Cnew = Snew.costEval(modules)
      if accept(Cnew - C, T):
        C, S = Cnew, Snew
        if minC >= Cnew:
          minC, minS = Cnew, Snew[:]
          Clist.append(Cnew)
          Temp.append(T)
    T = T * alpha
  if plot:
    import matplotlib.pyplot as plt
    plt.plot(Temp, Clist)
    plt.xlim(max(Temp), min(Temp))
    plt.xscale('log')
  return minS, minC

def sp_floorplan(modules):
  S = SeqPair(modules)
  Tmax = sum([i._area for i in modules])
  Smin, Cmin = simulated_annealing(1, Tmax, 100, 0.9, S, modules, False)
  assert(len(Smin._coords) == len(Smin._ap) and (len(Smin._coords) == len(modules)))
  sol = [(Smin._coords[i], modules[i]._wh[Smin._ap[i]], modules[i]._name) for i in range(len(modules)) ]
  return (sol, Cmin)

def plot(coords):
  import matplotlib.pyplot as plt
  from matplotlib.patches import Rectangle

  fig, ax = plt.subplots()
  ax.plot([0, 0])
  ax.set_aspect('equal')
  ax.set_xlim(0,max([r[0][0] + r[1][0] for r in coords]))
  ax.set_ylim(0,max([r[0][1] + r[1][1] for r in coords]))

  for i,r in enumerate(coords):
    match i%4:
      case 3: hatch, color = '/+', 'red'
      case 2: hatch, color = '///', 'green'
      case 1: hatch, color = '/\//\//\/', 'blue'
      case _: hatch, color = '\\\\\\', 'gray'
    ax.add_patch(Rectangle(r[0], r[1][0], r[1][1],
              edgecolor = color, facecolor=color,
              hatch=hatch, fill = False,
              lw=2))
    ax.text(r[0][0] + r[1][0]//2, r[0][1] + r[1][1]//2, r[2], fontsize=8)
  plt.show()

#Example 1
import time
m = [Module(str(i), random.randint(10,100), [1.]) for i in range(10)]
sumarea = sum([i._area for i in m])
t = time.time()
sol, area = sp_floorplan(m)
print(f"runtime: ", time.time()-t)
print(f"area: ", area, "Utilisation: ", sumarea * 100./area)
#plot(sol)

#Example 2
import time
m = [
    Module('a', 16, [0.25, 4.0]),
    Module('b', 32, [0.5, 2.0]),
    Module('c', 27, [1./3, 3.0]),
    Module('d', 6, [6])
]
sumarea = sum([i._area for i in m])
t = time.time()
sol, area = sp_floorplan(m)
print(f"runtime: ", time.time()-t)
print(f"area: ", area, "Utilisation: ", sumarea * 100./area)
#plot(sol)